_BASE_: [
  '../datasets/coco_detection_instance.yml',
  '../runtime.yml',
  '_base_/optimizer_6x.yml',
  '_base_/rtdetr_r50vd.yml',
  '_base_/rtdetr_reader.yml',
]

weights: models/instance/rtdetr_r50vd_6x_coco/model_final
find_unused_parameters: True
log_iter: 200
