# detection_parameter
is_run_detection: False
choosed_detection_model: yolov5
infer_image: ""
infer_dir: ""

# yolov5 parameter

# rtdetr parameter
infer_output_folder: ""
object_detection_parameter["envs_path"],
object_detection_parameter["detection_script_path"],
object_detection_parameter["config_path"],
images_path,
detection_result_save_path,
0.6
False
True